### ISSUE TITLE
Horizontally Scrollable ion-tabs

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-v1#112]
_From @chiragandroid on July 5, 2016 6:22_

**Here I am requesting a new feature in ionic1 that is Horizontally Scrollable IONIC TAB**

Actually, in ionic forms there is a lot of question on this topic some of that I am mentioning here. 

[By Rakesh Gajjar](https://forum.ionicframework.com/t/how-to-make-horizontal-scrollable-tab-nav-i-have-got-more-then-5-ion-tab/15088)
[many more](https://forum.ionicframework.com/search?q=scrollable%20ion-tab)

When we put too many ion-tab in ion-tabs . all tab text end by ...  
![menu](https://cloud.githubusercontent.com/assets/11516494/16575510/76dfba00-42a6-11e6-8ade-55d5d416e11a.png)

so please make some feature that makes ionic tabs scrollable in ion-tabs.

Thank you.

_Copied from original issue: driftyco/ionic#7202_

**Comment by jgw96** [comment]
_From @oktav777 on July 5, 2016 9:3_

UPD: I thougth this thread is for Ionic2, so the solution was working only for Ionic2, sorry.

``` scss

ion-segment {
    justify-content: space-between;
    overflow: auto;

    &::-webkit-scrollbar {
        width: 0;
        height: 0;
        display: none;
    }

    ion-segment-button.segment-button {
        flex: 1 0 100px;
    }
}

```

this is if you want fixed width tabs, if you want various width you should switch from flex to block/inline-block

``` scss

ion-segment {
    display: block;
    white-space: nowrap;
    font-size: 0;
    overflow: auto;

    &::-webkit-scrollbar {
        width: 0;
        height: 0;
        display: none;
    }

    ion-segment-button.segment-button {
        display: inline-block;
        min-width: 100px;
        width: auto;
    }
}

```

here is for various width tabs

**Comment by jgw96** [comment]
_From @chiragandroid on July 6, 2016 5:48_

Hello @InfinityOne, 
I have used ion-tab and ion-tabs to show tabs and view so, will i need to write ion-tab in place of ion-segment.

And i am using Ionic 1. i think ion-segment is ionic2 topic

**Comment by jgw96** [comment]
_From @oktav777 on July 6, 2016 6:28_

@chiragandroid ohhh sorry, did not observed it's about v1 ionic :(

**Comment by jgw96** [comment]
_From @roshandhabekar on November 15, 2016 8:7_

@InfinityOne hey man thanks for your work , but when i used this code for ion-segment horizontal scroll,
it scrollable bu not able to swipe by touch ..

ion-segment {
    display: block;
    white-space: nowrap;
    font-size: 0;
    overflow: auto;

```
&::-webkit-scrollbar {
    width: 0;
    height: 0;
    display: none;
}

ion-segment-button.segment-button {
    display: inline-block;
    min-width: 100px;
    width: auto;
}
```

}

**Comment by jgw96** [comment]
_From @oktav777 on November 15, 2016 13:2_

@roshandhabekar sorry once again, but this was for ionic2...

**Comment by jgw96** [comment]
_From @roshandhabekar on November 18, 2016 10:17_

@InfinityOne ya man i am trying with ionic 2 , still have same swipe not working issue
Thanks Man ..!

**Comment by garry18** [comment]
it's not working in ionic2

**Comment by janpio** [comment]
Then please create an issue at the `ionic` repository, here is about `ionic v1` only.
Make sure to include all the necessary information.

**Comment by BassamHabash** [comment]
Hi , I'm also have same problem , there is any solution for it ? @jgw96

**Comment by johntheo** [comment]
Hi guys,

I am using Ionic 3 and with the following code I manage to get scrollable tabs. You didnt need to put the ion-segment inside a ion-scroll. Just put this on your scss file:
```css
ion-segment {
    display: block;
    white-space: nowrap;
    font-size: 0;
    overflow: auto;

    &::-webkit-scrollbar {
      width: 0;
      height: 0;
      display: none;
    }

    ion-segment-button.segment-button {
      display: inline-block;
      min-width: 110px;
      width: auto;
    }
  }
```
